#include <Python.h>

PyDoc_STRVAR(doc__dscdef,
"DSC definitions");

static struct PyModuleDef _dscdef_module = {
    PyModuleDef_HEAD_INIT,
    "_dscdef",
    doc__dscdef,
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit__dscdef(void) {
    PyObject *m = PyModule_Create(&_dscdef_module);
    if (m == NULL) {
        return NULL;
    }
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_Z", 0);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_Z", 0);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_BU", 2);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_BU", 2);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_WU", 3);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_WU", 3);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_LU", 4);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_LU", 4);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_QU", 5);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_QU", 5);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_OU", 25);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_OU", 25);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_B", 6);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_B", 6);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_W", 7);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_W", 7);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_L", 8);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_L", 8);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_Q", 9);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_Q", 9);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_O", 26);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_O", 26);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_F", 10);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_F", 10);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_D", 11);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_D", 11);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_G", 27);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_G", 27);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_H", 28);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_H", 28);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FC", 12);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FC", 12);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_DC", 13);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_DC", 13);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_GC", 29);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_GC", 29);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_HC", 30);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_HC", 30);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FS", 52);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FS", 52);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FT", 53);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FT", 53);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FSC", 54);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FSC", 54);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FTC", 55);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FTC", 55);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FX", 57);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FX", 57);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FXC", 58);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FXC", 58);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_CIT", 31);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_CIT", 31);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_T", 14);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_T", 14);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_VT", 37);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_VT", 37);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_T2", 38);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_T2", 38);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NU", 15);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NU", 15);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NL", 16);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NL", 16);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NLO", 17);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NLO", 17);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NR", 18);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NR", 18);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NRO", 19);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NRO", 19);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_NZ", 20);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_NZ", 20);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_P", 21);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_P", 21);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_V", 1);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_V", 1);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_VU", 34);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_VU", 34);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_ZI", 22);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_ZI", 22);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_ZEM", 23);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_ZEM", 23);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_DSC", 24);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_DSC", 24);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_BPV", 32);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_BPV", 32);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_BLV", 33);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_BLV", 33);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_ADT", 35);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_ADT", 35);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_CAD", 178);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_CAD", 178);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_ENT", 179);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_ENT", 179);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_GBL", 180);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_GBL", 180);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_EPT", 181);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_EPT", 181);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_R11", 182);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_R11", 182);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_FLD", 183);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_FLD", 183);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_PCT", 184);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_PCT", 184);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_DPC", 185);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_DPC", 185);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_LBL", 186);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_LBL", 186);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_SLB", 187);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_SLB", 187);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_MOD", 188);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_MOD", 188);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_EOM", 189);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_EOM", 189);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_RTN", 190);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_RTN", 190);
    PyModule_AddIntConstant(m, "DSC_K_DTYPE_EOR", 191);
    PyModule_AddIntConstant(m, "DSC64_K_DTYPE_EOR", 191);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_Z", 0);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_Z", 0);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_S", 1);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_S", 1);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_D", 2);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_D", 2);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_V", 3);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_V", 3);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_A", 4);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_A", 4);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_P", 5);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_P", 5);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_PI", 6);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_PI", 6);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_J", 7);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_J", 7);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_JI", 8);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_SD", 9);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_SD", 9);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_NCA", 10);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_NCA", 10);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_VS", 11);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_VS", 11);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_VSA", 12);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_VSA", 12);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_UBS", 13);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_UBS", 13);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_UBA", 14);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_UBA", 14);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_SB", 15);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_SB", 15);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_UBSB", 16);
    PyModule_AddIntConstant(m, "DSC64_K_CLASS_UBSB", 16);
    PyModule_AddIntConstant(m, "DSC_K_CLASS_BFA", 191);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF", 14);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF1", 8);
    PyModule_AddIntConstant(m, "DSC_K_Z_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_Z_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_K_S_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_S_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_K_D_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_D_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_K_P_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_P_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_K_J_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_J_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_K_VS_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_C_VS_BLN", 8);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF2", 8);
    PyModule_AddIntConstant(m, "DSC_K_UBS_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_C_UBS_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF3", 12);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF4", 12);
    PyModule_AddIntConstant(m, "DSC_K_SD_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_C_SD_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF5", 20);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF6", 28);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF7", 28);
    PyModule_AddIntConstant(m, "DSC_K_PI_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_C_PI_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_K_JI_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_C_JI_BLN", 12);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF8", 12);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF9", 16);
    PyModule_AddIntConstant(m, "DSC_S_DSCDEF10", 20);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF64", 16);
    PyModule_AddIntConstant(m, "DSC64_S_LENGTH", 8);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF1_64", 24);
    PyModule_AddIntConstant(m, "DSC64_S_MAXSTRLEN", 8);
    PyModule_AddIntConstant(m, "DSC64_S_POINTER", 8);
    PyModule_AddIntConstant(m, "DSC64_K_Z_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_Z_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_K_S_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_S_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_K_D_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_D_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_K_P_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_P_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_K_J_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_J_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_K_VS_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_C_VS_BLN", 24);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF2_64", 24);
    PyModule_AddIntConstant(m, "DSC64_S_BASE", 8);
    PyModule_AddIntConstant(m, "DSC64_K_UBS_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_C_UBS_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF3_64", 32);
    PyModule_AddIntConstant(m, "DSC64_S_POS", 8);
    PyModule_AddIntConstant(m, "DSC64_K_SD_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_C_SD_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF5_64", 48);
    PyModule_AddIntConstant(m, "DSC64_S_ARSIZE", 8);
    PyModule_AddIntConstant(m, "DSC64_S_A0", 8);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF6_64", 64);
    PyModule_AddIntConstant(m, "DSC64_S_V0", 8);
    PyModule_AddIntConstant(m, "DSC64_S_S1", 8);
    PyModule_AddIntConstant(m, "DSC64_S_S2", 8);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF7_64", 64);
    PyModule_AddIntConstant(m, "DSC64_S_M1", 8);
    PyModule_AddIntConstant(m, "DSC64_S_M2", 8);
    PyModule_AddIntConstant(m, "DSC64_K_PI_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_C_PI_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_K_JI_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_C_JI_BLN", 32);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF8_64", 32);
    PyModule_AddIntConstant(m, "DSC64_S_FRAME", 8);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF9_64", 40);
    PyModule_AddIntConstant(m, "DSC64_S_SB_L1", 8);
    PyModule_AddIntConstant(m, "DSC64_S_SB_U1", 8);
    PyModule_AddIntConstant(m, "DSC64_S_DSCDEF10_64", 48);
    PyModule_AddIntConstant(m, "DSC64_S_UBSB_L1", 8);
    PyModule_AddIntConstant(m, "DSC64_S_UBSB_U1", 8);
    return m;
}