#include <Python.h>

PyDoc_STRVAR(doc__regdef,
"REG definitions");

static struct PyModuleDef _regdef_module = {
    PyModuleDef_HEAD_INIT,
    "_regdef",
    doc__regdef,
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit__regdef(void) {
    PyObject *m = PyModule_Create(&_regdef_module);
    PyModule_AddIntConstant(m, "REG_FC_CLOSE_KEY",  1);
    PyModule_AddIntConstant(m, "REG_FC_CREATE_KEY",  2);
    PyModule_AddIntConstant(m, "REG_FC_DELETE_KEY",  3);
    PyModule_AddIntConstant(m, "REG_FC_DELETE_VALUE",  4);
    PyModule_AddIntConstant(m, "REG_FC_ENUM_KEY",  5);
    PyModule_AddIntConstant(m, "REG_FC_ENUM_VALUE",  6);
    PyModule_AddIntConstant(m, "REG_FC_FLUSH_KEY",  7);
    PyModule_AddIntConstant(m, "REG_FC_LOAD_KEY",  8);
    PyModule_AddIntConstant(m, "REG_FC_MODIFY_KEY",  9);
    PyModule_AddIntConstant(m, "REG_FC_MODIFY_TREE_KEY",  10);
    PyModule_AddIntConstant(m, "REG_FC_NOTIFY_CHANGE_KEY_VALUE",  11);
    PyModule_AddIntConstant(m, "REG_FC_OPEN_KEY",  12);
    PyModule_AddIntConstant(m, "REG_FC_QUERY_KEY",  13);
    PyModule_AddIntConstant(m, "REG_FC_QUERY_VALUE",  14);
    PyModule_AddIntConstant(m, "REG_FC_REPLACE_KEY",  15);
    PyModule_AddIntConstant(m, "REG_FC_RESTORE_KEY",  16);
    PyModule_AddIntConstant(m, "REG_FC_SAVE_KEY",  17);
    PyModule_AddIntConstant(m, "REG_FC_SEARCH_TREE_DATA",  18);
    PyModule_AddIntConstant(m, "REG_FC_SEARCH_TREE_KEY",  19);
    PyModule_AddIntConstant(m, "REG_FC_SEARCH_TREE_VALUE",  20);
    PyModule_AddIntConstant(m, "REG_FC_SET_VALUE",  21);
    PyModule_AddIntConstant(m, "REG_FC_UNLOAD_KEY",  22);
    PyModule_AddIntConstant(m, "REG_FC_GET_KEY_SECURITY",  23);
    PyModule_AddIntConstant(m, "REG_FC_SET_KEY_SECURITY",  24);
    PyModule_AddIntConstant(m, "REG_FC_GET_PERFORMANCE",  25);
    PyModule_AddIntConstant(m, "REG_FC_GET_FILE_INFO",  26);
    PyModule_AddIntConstant(m, "REG_FC_GET_FILE_UPDATE",  27);
    PyModule_AddIntConstant(m, "REG_FC_CREATE_DATABASE",  28);
    PyModule_AddIntConstant(m, "REG_FC_MAKE_SNAPSHOT",  29);
    PyModule_AddIntConstant(m, "REG_FC_ARCHIVE",  30);
    PyModule_AddIntConstant(m, "REG_FC_LAST",  31);
    PyModule_AddIntConstant(m, "REG_M_UNICODE_STRING",  8192);
    PyModule_AddIntConstant(m, "REG__TERMINATOR",  0);
    PyModule_AddIntConstant(m, "REG__SEPARATOR",  1);
    PyModule_AddIntConstant(m, "REG__SECPROFILE",  514);
    PyModule_AddIntConstant(m, "REG__REQUEST",  515);
    PyModule_AddIntConstant(m, "REG__ACMODE",  1284);
    PyModule_AddIntConstant(m, "REG__ACTIONCODE",  1285);
    PyModule_AddIntConstant(m, "REG__CACHEACTION",  1286);
    PyModule_AddIntConstant(m, "REG__CANCELNOTIFICATION",  519);
    PyModule_AddIntConstant(m, "REG__CLASSNAME",  264);
    PyModule_AddIntConstant(m, "REG__CLASSNAMEMAX",  1289);
    PyModule_AddIntConstant(m, "REG__CLASSNAMESIZE",  1290);
    PyModule_AddIntConstant(m, "REG__DATAFLAGS",  1547);
    PyModule_AddIntConstant(m, "REG__DATATYPE",  1292);
    PyModule_AddIntConstant(m, "REG__DISPOSITION",  1293);
    PyModule_AddIntConstant(m, "REG__FILEINFODATA",  526);
    PyModule_AddIntConstant(m, "REG__FILELOAD",  1807);
    PyModule_AddIntConstant(m, "REG__FILESAVE",  1808);
    PyModule_AddIntConstant(m, "REG__FILEUPDATEDATA",  529);
    PyModule_AddIntConstant(m, "REG__FLAGOPCODE",  1298);
    PyModule_AddIntConstant(m, "REG__FLAGSUBKEY",  1299);
    PyModule_AddIntConstant(m, "REG__KEYID",  1300);
    PyModule_AddIntConstant(m, "REG__KEYID_INTERNAL",  533);
    PyModule_AddIntConstant(m, "REG__KEYFLAGS",  1302);
    PyModule_AddIntConstant(m, "REG__KEYPATH",  279);
    PyModule_AddIntConstant(m, "REG__KEYRESULT",  1304);
    PyModule_AddIntConstant(m, "REG__KEYRESULT_INTERNAL",  537);
    PyModule_AddIntConstant(m, "REG__LASTWRITE",  1562);
    PyModule_AddIntConstant(m, "REG__LINKCOUNT",  1307);
    PyModule_AddIntConstant(m, "REG__LINKPATH",  284);
    PyModule_AddIntConstant(m, "REG__LINKPATHSIZE",  1309);
    PyModule_AddIntConstant(m, "REG__LINKTYPE",  1310);
    PyModule_AddIntConstant(m, "REG__LOCK",  1311);
    PyModule_AddIntConstant(m, "REG__NEWNAME",  288);
    PyModule_AddIntConstant(m, "REG__NOTIFYFILTER",  1313);
    PyModule_AddIntConstant(m, "REG__PATHBUFFER",  546);
    PyModule_AddIntConstant(m, "REG__PERFORMANCEDATA",  547);
    PyModule_AddIntConstant(m, "REG__REQLENGTH",  1316);
    PyModule_AddIntConstant(m, "REG__RETURNSTATUS",  1317);
    PyModule_AddIntConstant(m, "REG__SECACCESS",  1318);
    PyModule_AddIntConstant(m, "REG__SECONDSTATUS",  1319);
    PyModule_AddIntConstant(m, "REG__SECURITYPOLICY",  1320);
    PyModule_AddIntConstant(m, "REG__SEGMENTNUMBER",  1321);
    PyModule_AddIntConstant(m, "REG__SNAPSHOTDESTINATION",  1834);
    PyModule_AddIntConstant(m, "REG__SNAPSHOTVERSIONS",  1323);
    PyModule_AddIntConstant(m, "REG__SUBKEYINDEX",  1324);
    PyModule_AddIntConstant(m, "REG__SUBKEYNAME",  301);
    PyModule_AddIntConstant(m, "REG__SUBKEYNAMEMAX",  1326);
    PyModule_AddIntConstant(m, "REG__SUBKEYNAMESIZE",  1327);
    PyModule_AddIntConstant(m, "REG__SUBKEYSNUMBER",  1328);
    PyModule_AddIntConstant(m, "REG__SECURITYINFORMATION",  1329);
    PyModule_AddIntConstant(m, "REG__SECURITYDESCRIPTOR",  562);
    PyModule_AddIntConstant(m, "REG__VALUEINDEX",  1331);
    PyModule_AddIntConstant(m, "REG__VALUEDATA",  564);
    PyModule_AddIntConstant(m, "REG__VALUEDATAMAX",  1333);
    PyModule_AddIntConstant(m, "REG__VALUEDATASIZE",  1334);
    PyModule_AddIntConstant(m, "REG__VALUENAME",  311);
    PyModule_AddIntConstant(m, "REG__VALUENAMEMAX",  1336);
    PyModule_AddIntConstant(m, "REG__VALUENAMESIZE",  1337);
    PyModule_AddIntConstant(m, "REG__VALUENUMBER",  1338);
    PyModule_AddIntConstant(m, "REG__VOLATILE",  1339);
    PyModule_AddIntConstant(m, "REG__WILDASTERISK",  316);
    PyModule_AddIntConstant(m, "REG__WILDPERCENT",  317);
    PyModule_AddIntConstant(m, "REG__WILDPERIODS",  318);
    PyModule_AddIntConstant(m, "REG__INSTRUMENTFILE",  575);
    PyModule_AddIntConstant(m, "REG__INSTRUMENTKEY",  576);
    PyModule_AddIntConstant(m, "REG__INSTRUMENTDATA",  577);
    PyModule_AddIntConstant(m, "REG__FILENAME",  1858);
    PyModule_AddIntConstant(m, "REG__COUNTER",  1347);
    PyModule_AddIntConstant(m, "REG__SECDESCRIPTORLEN",  1348);
    PyModule_AddIntConstant(m, "REG__SECDESCLEN_INTERNAL",  1349);
    PyModule_AddIntConstant(m, "REG__VALUEDATASIZE_INTERNAL",  1350);
    PyModule_AddIntConstant(m, "REG__SAMDESIRED",  1351);
    PyModule_AddIntConstant(m, "REG__DATABASE_VERSION",  1352);
    PyModule_AddIntConstant(m, "REG__LAST",  73);
    PyModule_AddIntConstant(m, "REG_K_NONE",  0);
    PyModule_AddIntConstant(m, "REG_K_CLUSTER",  1);
    PyModule_AddIntConstant(m, "REG_K_SYSTEM",  2);
    PyModule_AddIntConstant(m, "REG_K_PROCESS",  3);
    PyModule_AddIntConstant(m, "REG_K_IMAGE",  4);
    PyModule_AddIntConstant(m, "REG_K_WRITEBEHIND",  5);
    PyModule_AddIntConstant(m, "REG_K_WRITETHRU",  6);
    PyModule_AddIntConstant(m, "REG_K_CREATENEWKEY",  7);
    PyModule_AddIntConstant(m, "REG_K_OPENEXISTINGKEY",  8);
    PyModule_AddIntConstant(m, "REG_K_POLICY_OPENVMS",  9);
    PyModule_AddIntConstant(m, "REG_K_POLICY_NT_40",  10);
    PyModule_AddIntConstant(m, "REG_K_INTERNAL",  11);
    PyModule_AddIntConstant(m, "REG_K_HARDLINK",  12);
    PyModule_AddIntConstant(m, "REG_K_SYMBOLICLINK",  13);
    PyModule_AddIntConstant(m, "REG_K_BINARY",  14);
    PyModule_AddIntConstant(m, "REG_K_DWORD",  15);
    PyModule_AddIntConstant(m, "REG_K_DWLITTLEENDIAN",  16);
    PyModule_AddIntConstant(m, "REG_K_DWBIGENDIAN",  17);
    PyModule_AddIntConstant(m, "REG_K_EXPAND_SZ",  18);
    PyModule_AddIntConstant(m, "REG_K_LINK",  19);
    PyModule_AddIntConstant(m, "REG_K_MULTI_SZ",  20);
    PyModule_AddIntConstant(m, "REG_K_QWORD",  21);
    PyModule_AddIntConstant(m, "REG_K_RESOURCELIST",  22);
    PyModule_AddIntConstant(m, "REG_K_SZ",  23);
    PyModule_AddIntConstant(m, "REG_K_START_FILE",  24);
    PyModule_AddIntConstant(m, "REG_K_START_PERF",  25);
    PyModule_AddIntConstant(m, "REG_K_STOP_FILE",  26);
    PyModule_AddIntConstant(m, "REG_K_STOP_PERF",  27);
    PyModule_AddIntConstant(m, "REG_K_ZERO_FILE",  28);
    PyModule_AddIntConstant(m, "REG_K_ZERO_PERF",  29);
    PyModule_AddIntConstant(m, "REG_K_SHOW_CTR_FILE",  30);
    PyModule_AddIntConstant(m, "REG_K_SHOW_CTR_PERF",  31);
    PyModule_AddIntConstant(m, "REG_K_SHOW_FILE",  32);
    PyModule_AddIntConstant(m, "REG_K_NORMAL",  33);
    PyModule_AddIntConstant(m, "REG_K_LARGE",  34);
    PyModule_AddIntConstant(m, "REG_K_EXACTMATCH",  35);
    PyModule_AddIntConstant(m, "REG_K_INCLUDE",  36);
    PyModule_AddIntConstant(m, "REG_K_EXCLUDE",  37);
    PyModule_AddIntConstant(m, "REG_K_ANY",  38);
    PyModule_AddIntConstant(m, "REG_K_NOTANY",  39);
    PyModule_AddIntConstant(m, "REG_M_FC",  0x3FFL);
    PyModule_AddIntConstant(m, "REG_M_CASE_SENSITIVE",  0x400L);
    PyModule_AddIntConstant(m, "REG_M_DISABLE_WILDCARDS",  0x800L);
    PyModule_AddIntConstant(m, "REG_M_IGNORE_LINKS",  0x1000L);
    PyModule_AddIntConstant(m, "REG_M_NOW",  0x2000L);
    PyModule_AddIntConstant(m, "REG_M_NOWAIT",  0x4000L);
    PyModule_AddIntConstant(m, "REG_M_UNICODE_VALUES",  0x8000L);
    PyModule_AddIntConstant(m, "REG_M_BYPASS",  0x10000L);
    PyModule_AddIntConstant(m, "REG_M_INTERNAL",  0x20000L);
    PyModule_AddIntConstant(m, "REG_S_REGDEF",  3);
    PyModule_AddIntConstant(m, "REG_S_FC",  10);
    PyModule_AddIntConstant(m, "REG_M_CHANGENAME",  0x1L);
    PyModule_AddIntConstant(m, "REG_M_CHANGEATTRIBUTES",  0x2L);
    PyModule_AddIntConstant(m, "REG_M_CHANGELASTSET",  0x4L);
    PyModule_AddIntConstant(m, "REG_M_CHANGESECURITY",  0x8L);
    PyModule_AddIntConstant(m, "REG_S_KEYCHANGEDEF",  1);
    PyModule_AddIntConstant(m, "REG_M_ALLACCESS",  0x1L);
    PyModule_AddIntConstant(m, "REG_M_CREATELINK",  0x2L);
    PyModule_AddIntConstant(m, "REG_M_CREATESUBKEY",  0x4L);
    PyModule_AddIntConstant(m, "REG_M_ENUMSUBKEYS",  0x8L);
    PyModule_AddIntConstant(m, "REG_M_EXECUTE",  0x10L);
    PyModule_AddIntConstant(m, "REG_M_NOTIFY",  0x20L);
    PyModule_AddIntConstant(m, "REG_M_QUERYVALUE",  0x40L);
    PyModule_AddIntConstant(m, "REG_M_READ",  0x80L);
    PyModule_AddIntConstant(m, "REG_M_SETVALUE",  0x100L);
    PyModule_AddIntConstant(m, "REG_M_WRITE",  0x200L);
    PyModule_AddIntConstant(m, "REG_M_DELETEACCESS",  0x400L);
    PyModule_AddIntConstant(m, "REG_M_READCONTROL",  0x800L);
    PyModule_AddIntConstant(m, "REG_M_WRITEDAC",  0x1000L);
    PyModule_AddIntConstant(m, "REG_M_WRITEOWNER",  0x2000L);
    PyModule_AddIntConstant(m, "REG_M_SYNCHRONIZE",  0x4000L);
    PyModule_AddIntConstant(m, "REG_M_ACCESSSYSTEMSECURITY",  0x8000L);
    PyModule_AddIntConstant(m, "REG_M_MAXIMUMALLOWED",  0x10000L);
    PyModule_AddIntConstant(m, "REG_M_GENERICALL",  0x20000L);
    PyModule_AddIntConstant(m, "REG_M_GENERICEXECUTE",  0x40000L);
    PyModule_AddIntConstant(m, "REG_M_GENERICWRITE",  0x80000L);
    PyModule_AddIntConstant(m, "REG_M_GENERICREAD",  0x100000L);
    PyModule_AddIntConstant(m, "REG_S_SECACCESSDEF",  3);
    PyModule_AddIntConstant(m, "REG__HKEY_NONE",  0);
    PyModule_AddIntConstant(m, "REG__HKEY_CLASSES_ROOT",  -2147483648);
    PyModule_AddIntConstant(m, "REG__HKEY_CURRENT_USER",  -2147483647);
    PyModule_AddIntConstant(m, "REG__HKEY_LOCAL_MACHINE",  -2147483646);
    PyModule_AddIntConstant(m, "REG__HKEY_USERS",  -2147483645);
    PyModule_AddIntConstant(m, "REG__HKEY_PERFORMANCE_DATA",  -2147483644);
    PyModule_AddIntConstant(m, "REG__HKEY_LAST_ROOT_KEY",  5);
   return m;
}