#include <Python.h>

PyDoc_STRVAR(doc__prdef,
"PR definitions");

static struct PyModuleDef _prdef_module = {
    PyModuleDef_HEAD_INIT,
    "_prdef",
    doc__prdef,
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit__prdef(void) {
    PyObject *m = PyModule_Create(&_prdef_module);
    if (m == NULL) {
        return NULL;
    }
    PyModule_AddIntConstant(m, "PR__ESP", 1);
    PyModule_AddIntConstant(m, "PR__SSP", 2);
    PyModule_AddIntConstant(m, "PR__USP", 3);
    PyModule_AddIntConstant(m, "PR__ASN", 6);
    PyModule_AddIntConstant(m, "PR__ASTEN", 48);
    PyModule_AddIntConstant(m, "PR__ASTSR", 49);
    PyModule_AddIntConstant(m, "PR__DATFX", 23);
    PyModule_AddIntConstant(m, "PR__IPIR", 22);
    PyModule_AddIntConstant(m, "PR__IPL", 18);
    PyModule_AddIntConstant(m, "PR__MCES", 38);
    PyModule_AddIntConstant(m, "PR__PCBB", 16);
    PyModule_AddIntConstant(m, "PR__PME", 61);
    PyModule_AddIntConstant(m, "PR__PRBR", 15);
    PyModule_AddIntConstant(m, "PR__SCBB", 17);
    PyModule_AddIntConstant(m, "PR__SIRR", 20);
    PyModule_AddIntConstant(m, "PR__SISR", 21);
    PyModule_AddIntConstant(m, "PR__TBIA", 57);
    PyModule_AddIntConstant(m, "PR__TBIAP", 50);
    PyModule_AddIntConstant(m, "PR__TBIS", 58);
    PyModule_AddIntConstant(m, "PR__TBIS_64", 60);
    PyModule_AddIntConstant(m, "PR__TBISD", 59);
    PyModule_AddIntConstant(m, "PR__TBISI", 47);
    PyModule_AddIntConstant(m, "PR__VPTB", 12);
    PyModule_AddIntConstant(m, "PR__SID_TYP780", 1);
    PyModule_AddIntConstant(m, "PR__SID_TYP750", 2);
    PyModule_AddIntConstant(m, "PR__SID_TYP730", 3);
    PyModule_AddIntConstant(m, "PR__SID_TYP790", 4);
    PyModule_AddIntConstant(m, "PR__SID_TYP8SS", 5);
    PyModule_AddIntConstant(m, "PR__SID_TYP8NN", 6);
    PyModule_AddIntConstant(m, "PR__SID_TYPUV1", 7);
    PyModule_AddIntConstant(m, "PR__SID_TYPUV2", 8);
    PyModule_AddIntConstant(m, "PR__SID_TYP410", 8);
    PyModule_AddIntConstant(m, "PR__SID_TYP009", 9);
    PyModule_AddIntConstant(m, "PR__SID_TYP420", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP520", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP650", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP9CC", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP9CI", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP60", 10);
    PyModule_AddIntConstant(m, "PR__SID_TYP670", 11);
    PyModule_AddIntConstant(m, "PR__SID_TYP9RR", 11);
    PyModule_AddIntConstant(m, "PR__SID_TYP43", 11);
    PyModule_AddIntConstant(m, "PR__SID_TYP9AQ", 14);
    PyModule_AddIntConstant(m, "PR__SID_TYP8PS", 17);
    PyModule_AddIntConstant(m, "PR__SID_TYP1202", 18);
    PyModule_AddIntConstant(m, "PR__SID_TYP46", 18);
    PyModule_AddIntConstant(m, "PR__SID_TYP600", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP690", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP700", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP1302", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP49", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP1303", 19);
    PyModule_AddIntConstant(m, "PR__SID_TYP660", 20);
    PyModule_AddIntConstant(m, "PR__SID_TYP440", 20);
    PyModule_AddIntConstant(m, "PR__SID_TYP4A", 20);
    PyModule_AddIntConstant(m, "PR__SID_TYP550", 20);
    PyModule_AddIntConstant(m, "PR__SID_TYP1701", 23);
    PyModule_AddIntConstant(m, "PR__SID_TYPMAX", 23);
    PyModule_AddIntConstant(m, "PR__SID_TYP_NOTAVAX", 128);
    PyModule_AddIntConstant(m, "PR__SID_TYPUV", 8);
    PyModule_AddIntConstant(m, "PR__XSID_UV_UV", 0);
    PyModule_AddIntConstant(m, "PR__XSID_UV_UV2", 1);
    PyModule_AddIntConstant(m, "PR__XSID_UV_410", 4);
    PyModule_AddIntConstant(m, "PR__SID_TYPCV", 10);
    PyModule_AddIntConstant(m, "PR__XSID_CV_CV", 0);
    PyModule_AddIntConstant(m, "PR__XSID_CV_650", 1);
    PyModule_AddIntConstant(m, "PR__XSID_CV_9CC", 2);
    PyModule_AddIntConstant(m, "PR__XSID_CV_60", 3);
    PyModule_AddIntConstant(m, "PR__XSID_CV_420", 4);
    PyModule_AddIntConstant(m, "PR__XSID_CV_9CI", 5);
    PyModule_AddIntConstant(m, "PR__XSID_CV_520", 7);
    PyModule_AddIntConstant(m, "PR__SID_TYPRV", 11);
    PyModule_AddIntConstant(m, "PR__XSID_RV_RV", 0);
    PyModule_AddIntConstant(m, "PR__XSID_RV_670", 1);
    PyModule_AddIntConstant(m, "PR__XSID_RV_9RR", 2);
    PyModule_AddIntConstant(m, "PR__XSID_RV_43", 4);
    PyModule_AddIntConstant(m, "PR__SID_TYPV12", 18);
    PyModule_AddIntConstant(m, "PR__XSID_V12_V12", 0);
    PyModule_AddIntConstant(m, "PR__XSID_V12_1202", 2);
    PyModule_AddIntConstant(m, "PR__XSID_V12_46", 4);
    PyModule_AddIntConstant(m, "PR__SID_TYPV13", 19);
    PyModule_AddIntConstant(m, "PR__XSID_V13_V13", 0);
    PyModule_AddIntConstant(m, "PR__XSID_V13_690", 1);
    PyModule_AddIntConstant(m, "PR__XSID_V13_1302", 2);
    PyModule_AddIntConstant(m, "PR__XSID_V13_1303", 3);
    PyModule_AddIntConstant(m, "PR__XSID_V13_49", 4);
    PyModule_AddIntConstant(m, "PR__XSID_V13_700", 5);
    PyModule_AddIntConstant(m, "PR__XSID_V13_600", 6);
    PyModule_AddIntConstant(m, "PR__SID_TYPV14", 20);
    PyModule_AddIntConstant(m, "PR__XSID_V14_V14", 0);
    PyModule_AddIntConstant(m, "PR__XSID_V14_660", 1);
    PyModule_AddIntConstant(m, "PR__XSID_V14_440", 4);
    PyModule_AddIntConstant(m, "PR__XSID_V14_4A", 5);
    PyModule_AddIntConstant(m, "PR__XSID_V14_550", 7);
    PyModule_AddIntConstant(m, "PR__SID_TYPV17", 23);
    PyModule_AddIntConstant(m, "PR__XSID_V17_V17", 0);
    PyModule_AddIntConstant(m, "PR__XSID_V17_1701", 1);
    PyModule_AddIntConstant(m, "PR__XSID_N8800", 0);
    PyModule_AddIntConstant(m, "PR__XSID_N8700", 1);
    PyModule_AddIntConstant(m, "PR__XSID_N2", 2);
    PyModule_AddIntConstant(m, "PR__XSID_N3", 3);
    PyModule_AddIntConstant(m, "PR__XSID_N4", 4);
    PyModule_AddIntConstant(m, "PR__XSID_N5", 5);
    PyModule_AddIntConstant(m, "PR__XSID_N8550", 6);
    PyModule_AddIntConstant(m, "PR__XSID_N8500", 7);
    PyModule_AddIntConstant(m, "PR__XSID_N8NNN", -1);
    PyModule_AddIntConstant(m, "PR_M_ASTEN", 0xFL);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_KEN", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_EEN", 0x2L);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_SEN", 0x4L);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_UEN", 0x8L);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_DSBL_ALL", 0);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_ENBL_ALL", 255);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_ENBL_K", 17);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_ENBL_E", 34);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_ENBL_S", 68);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_ENBL_U", 136);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_PRSRV_ALL", 15);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_PRSRV_K", 1);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_PRSRV_E", 2);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_PRSRV_S", 4);
    PyModule_AddIntConstant(m, "PR_M_ASTEN_PRSRV_U", 8);
    PyModule_AddIntConstant(m, "PR_M_ASTSR", 0xFL);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_KPD", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_EPD", 0x2L);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SPD", 0x4L);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_UPD", 0x8L);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_CLR_ALL", 0);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SET_ALL", 255);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SET_K", 17);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SET_E", 34);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SET_S", 68);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_SET_U", 136);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_PRSRV_ALL", 15);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_PRSRV_K", 1);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_PRSRV_E", 2);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_PRSRV_S", 4);
    PyModule_AddIntConstant(m, "PR_M_ASTSR_PRSRV_U", 8);
    PyModule_AddIntConstant(m, "PR_M_FEN_FEN", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_DATFX_DATFX", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_IPL_IPL", 0x1FL);
    PyModule_AddIntConstant(m, "PR_M_MCES_MCK", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_MCES_SCE", 0x2L);
    PyModule_AddIntConstant(m, "PR_M_MCES_PCE", 0x4L);
    PyModule_AddIntConstant(m, "PR_M_MCES_DPC", 0x8L);
    PyModule_AddIntConstant(m, "PR_M_MCES_DSC", 0x10L);
    PyModule_AddIntConstant(m, "PR_V_PCBB_PA", 0);
    PyModule_AddIntConstant(m, "PR_S_PCBB_PA", 48);
    PyModule_AddIntConstant(m, "PR_M_PS_SW", 0x3L);
    PyModule_AddIntConstant(m, "PR_M_PS_PRVMOD", 0x3L);
    PyModule_AddIntConstant(m, "PR_M_PS_SYSSTATE", 0x4L);
    PyModule_AddIntConstant(m, "PR_M_PS_CURMOD", 0x18L);
    PyModule_AddIntConstant(m, "PR_M_PS_VMM", 0x80L);
    PyModule_AddIntConstant(m, "PR_M_PS_IPL", 0x1F00L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_PS_SP_ALIGN", 0x3F00000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_PS_MBZ_62", 0x4000000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_PS_MBZ_63", 0x8000000000000000L);
    PyModule_AddIntConstant(m, "PR_V_PS_MAX_PS_REG_BIT", 13);
    PyModule_AddIntConstant(m, "PR_C_PS_KERNEL", 0);
    PyModule_AddIntConstant(m, "PR_C_PS_EXEC", 1);
    PyModule_AddIntConstant(m, "PR_C_PS_SUPER", 2);
    PyModule_AddIntConstant(m, "PR_C_PS_USER", 3);
    PyModule_AddIntConstant(m, "PR_M_PTBR_PFN", 0xFFFFFFFFL);
    PyModule_AddIntConstant(m, "PR_M_SCBB_PFN", 0xFFFFFFFFL);
    PyModule_AddIntConstant(m, "PR_M_SIRR_LVL", 0xFL);
    PyModule_AddIntConstant(m, "PR_M_SISR_SUMMARY", 0xFFFFL);
    PyModule_AddIntConstant(m, "PR_M_SISR_RAZ", 0x1L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR1", 0x2L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR2", 0x4L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR3", 0x8L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR4", 0x10L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR5", 0x20L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR6", 0x40L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR7", 0x80L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR8", 0x100L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR9", 0x200L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR10", 0x400L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR11", 0x800L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR12", 0x1000L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR13", 0x2000L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR14", 0x4000L);
    PyModule_AddIntConstant(m, "PR_M_SISR_IR15", 0x8000L);
    PyModule_AddIntConstant(m, "PR_M_TBCHK_VA_PRESENT", 0x1L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_DNOD", 0x800000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_DNZ", 0x1000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_INVD", 0x2000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_DZED", 0x4000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_OVFD", 0x8000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_INV", 0x10000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_DZE", 0x20000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_OVF", 0x40000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_UNF", 0x80000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_INE", 0x100000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_IOV", 0x200000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_UNDZ", 0x1000000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_UNFD", 0x2000000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_INED", 0x4000000000000000L);
    PyModule_AddUnsignedLongLongConstant(m, "PR_M_IEEE_SUMMARY", 0x8000000000000000L);
    PyModule_AddIntConstant(m, "PR_S_PRDEF", 8);
    PyModule_AddIntConstant(m, "PR_S_QUAD_ACCESS", 8);
    PyModule_AddIntConstant(m, "PR_S_LONG_ACCESS", 8);
    PyModule_AddIntConstant(m, "PR_S_SID_SN", 12);
    PyModule_AddIntConstant(m, "PR_S_SID_PL", 3);
    PyModule_AddIntConstant(m, "PR_S_SID_ECO", 9);
    PyModule_AddIntConstant(m, "PR_S_SID_TYPE", 8);
    PyModule_AddIntConstant(m, "PR_S_XSID_TYPE", 8);
    PyModule_AddIntConstant(m, "PR_S_ASTEN", 4);
    PyModule_AddIntConstant(m, "PR_S_ASTSR", 4);
    PyModule_AddIntConstant(m, "PR_S_IPL_IPL", 5);
    PyModule_AddIntConstant(m, "PR_S_PS_SW", 2);
    PyModule_AddIntConstant(m, "PR_S_PS_PRVMOD", 2);
    PyModule_AddIntConstant(m, "PR_S_PS_CURMOD", 2);
    PyModule_AddIntConstant(m, "PR_S_PS_IPL", 5);
    PyModule_AddIntConstant(m, "PR_S_PS_SP_ALIGN", 6);
    PyModule_AddIntConstant(m, "PR_S_PTBR_PFN", 32);
    PyModule_AddIntConstant(m, "PR_S_SCBB_PFN", 32);
    PyModule_AddIntConstant(m, "PR_S_SIRR_LVL", 4);
    PyModule_AddIntConstant(m, "PR_S_SISR_SUMMARY", 16);
    PyModule_AddIntConstant(m, "PR_S_IEEE_DYN_RND", 2);
    return m;
}